ID=ru.litres.plugin.publish.samsung
VERSION=0.0.8
GROUP=ru.litres.plugin
DISPLAY_NAME=Samsung publisher
DESCRIPTION=Gradle plugin for publish in samsung store
WEBSITE=https://github.com/Litres/samsung-publisher-gradle-plugin
VCS_URL=https://github.com/Litres/samsung-publisher-gradle-plugin
IMPLEMENTATION_CLASS=ru.litres.publish.samsung.SamsungPublishPlugin
